/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.MPedido;
import model.MProduto;
import tipos.TPessoaJuridica;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import tipos.TItemPedido;
import tipos.TProduto;

/**
 *
 * @author leo_m
 */
public class VCadastroPedido extends javax.swing.JFrame {

    MPedido model = new MPedido();

    private void carregaListaProduto() {
        List<TProduto> prod = new TProduto().getProdutos();
        for (TProduto i : prod) {
            cbProduto.addItem(i);
        }
    }

    private void inicializaComponentes() {
        jtProdutos.setModel((TableModel) model);

        carregaListaPessoa();
        carregaListaProduto();
//        carregaListaVendedor();
        AutoCompleteDecorator.decorate(cbRazaoSocial);
        cbRazaoSocial.setSelectedItem(null);
        AutoCompleteDecorator.decorate(cbProduto);
        cbProduto.setSelectedItem(null);
        AutoCompleteDecorator.decorate(cbVendedor);
        cbVendedor.setSelectedItem(null);

    }

    private void carregaListaPessoa() {

        List<TPessoaJuridica> cat = new TPessoaJuridica().getPessoasJuridicas();
        for (TPessoaJuridica i : cat) {
            cbRazaoSocial.addItem(i);
        }

    }

    /**
     * Creates new form VCadastroPedido
     */
    public VCadastroPedido() {
        initComponents();
        inicializaComponentes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInfos = new javax.swing.JPanel();
        cbRazaoSocial = new javax.swing.JComboBox<>();
        lbCliente = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        lbVendedor = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        btnCadastrarCliente = new javax.swing.JButton();
        cbVendedor = new javax.swing.JComboBox<>();
        tfNumero = new javax.swing.JTextField();
        lbNumero = new javax.swing.JLabel();
        jspEndereco = new javax.swing.JScrollPane();
        taEndereco = new javax.swing.JTextArea();
        lbCidade = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        lbNf = new javax.swing.JLabel();
        tfNf = new javax.swing.JTextField();
        ftfData = new javax.swing.JFormattedTextField();
        ftfTelefone = new javax.swing.JFormattedTextField();
        jProdutos = new javax.swing.JPanel();
        lbProduto = new javax.swing.JLabel();
        lbQuantidade = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        cbProduto = new javax.swing.JComboBox<>();
        tfQuantidade = new javax.swing.JTextField();
        lbUnidadeMedida = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtProdutos = new javax.swing.JTable();
        lbTotal = new javax.swing.JLabel();
        lbNroTotal = new javax.swing.JLabel();
        btnRemover = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jRodape = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInfos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Geral", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lbCliente.setText("Cliente");

        lbTelefone.setText("Telefone");

        lbVendedor.setText("Vendedor");

        lbEndereco.setText("Endereço");

        lbData.setText("Data");

        btnCadastrarCliente.setText("+");

        lbNumero.setText("Número");

        taEndereco.setColumns(20);
        taEndereco.setRows(5);
        jspEndereco.setViewportView(taEndereco);

        lbCidade.setText("Cidade");

        lbNf.setText("NF");

        javax.swing.GroupLayout jInfosLayout = new javax.swing.GroupLayout(jInfos);
        jInfos.setLayout(jInfosLayout);
        jInfosLayout.setHorizontalGroup(
            jInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInfosLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jspEndereco)
                    .addGroup(jInfosLayout.createSequentialGroup()
                        .addComponent(cbRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastrarCliente))
                    .addComponent(lbCliente)
                    .addGroup(jInfosLayout.createSequentialGroup()
                        .addGroup(jInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInfosLayout.createSequentialGroup()
                                .addGroup(jInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTelefone)
                                    .addComponent(lbEndereco))
                                .addGap(83, 83, 83))
                            .addGroup(jInfosLayout.createSequentialGroup()
                                .addComponent(ftfTelefone)
                                .addGap(18, 18, 18)))
                        .addGroup(jInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCidade)
                            .addComponent(tfCidade))))
                .addGap(92, 92, 92)
                .addGroup(jInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInfosLayout.createSequentialGroup()
                        .addGroup(jInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbNf)
                                .addComponent(tfNf)
                                .addComponent(lbVendedor)
                                .addComponent(cbVendedor, 0, 172, Short.MAX_VALUE))
                            .addGroup(jInfosLayout.createSequentialGroup()
                                .addComponent(ftfData, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(jInfosLayout.createSequentialGroup()
                        .addComponent(lbData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNumero)
                        .addGap(74, 74, 74))))
        );
        jInfosLayout.setVerticalGroup(
            jInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInfosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInfosLayout.createSequentialGroup()
                        .addComponent(lbCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastrarCliente))
                        .addGap(10, 10, 10)
                        .addGroup(jInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTelefone)
                            .addComponent(lbCidade)
                            .addComponent(lbNf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfNf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInfosLayout.createSequentialGroup()
                        .addGroup(jInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbData)
                            .addComponent(lbNumero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbEndereco)
                    .addComponent(lbVendedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jInfosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lbProduto.setText("Produto");

        lbQuantidade.setText("Quantidade");

        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        lbUnidadeMedida.setText("un");

        jtProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtProdutos);

        lbTotal.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbTotal.setText("Total:");

        lbNroTotal.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        lbNroTotal.setText("0,00");

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jProdutosLayout = new javax.swing.GroupLayout(jProdutos);
        jProdutos.setLayout(jProdutosLayout);
        jProdutosLayout.setHorizontalGroup(
            jProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jProdutosLayout.createSequentialGroup()
                .addGroup(jProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jProdutosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbNroTotal)
                        .addGap(8, 8, 8))
                    .addGroup(jProdutosLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(jProdutosLayout.createSequentialGroup()
                                .addGroup(jProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbProduto)
                                    .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jProdutosLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(lbQuantidade))
                                    .addGroup(jProdutosLayout.createSequentialGroup()
                                        .addComponent(tfQuantidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbUnidadeMedida)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnAdicionar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnRemover)
                                        .addGap(12, 12, 12)
                                        .addComponent(btnAlterar)
                                        .addGap(1, 1, 1)))))))
                .addGap(62, 62, 62))
        );
        jProdutosLayout.setVerticalGroup(
            jProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbProduto)
                    .addComponent(lbQuantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(cbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUnidadeMedida)
                    .addComponent(btnRemover)
                    .addComponent(btnAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTotal)
                    .addComponent(lbNroTotal))
                .addContainerGap())
        );

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout jRodapeLayout = new javax.swing.GroupLayout(jRodape);
        jRodape.setLayout(jRodapeLayout);
        jRodapeLayout.setHorizontalGroup(
            jRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jRodapeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar)
                .addGap(32, 32, 32))
        );
        jRodapeLayout.setVerticalGroup(
            jRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jRodapeLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jRodapeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnCadastrar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInfos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jRodape, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInfos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jRodape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        System.out.println(cbRazaoSocial.getSelectedItem().toString());
    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        TItemPedido item = new TItemPedido();
        item.setProduto((TProduto) cbProduto.getSelectedItem());
        item.setQuantidade(Integer.parseInt(tfQuantidade.getText()));
        item.calculaValor();
        model.addRow(item);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (jtProdutos.getSelectedRow() != -1) {
            model.removeRow(jtProdutos.getSelectedRow());
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        if (jtProdutos.getSelectedRow() != -1) {
            model.setValueAt(cbProduto, jtProdutos.getSelectedRow(), 0);
            model.setValueAt(cbProduto, jtProdutos.getSelectedRow(), 1);
            model.setValueAt(cbProduto, jtProdutos.getSelectedRow(), 2);
            model.setValueAt(cbProduto, jtProdutos.getSelectedRow(), 3);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCadastroPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCadastroPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox<Object> cbProduto;
    private javax.swing.JComboBox<Object> cbRazaoSocial;
    private javax.swing.JComboBox<Object> cbVendedor;
    private javax.swing.JFormattedTextField ftfData;
    private javax.swing.JFormattedTextField ftfTelefone;
    private javax.swing.JPanel jInfos;
    private javax.swing.JPanel jProdutos;
    private javax.swing.JPanel jRodape;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jspEndereco;
    private javax.swing.JTable jtProdutos;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbNf;
    private javax.swing.JLabel lbNroTotal;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbProduto;
    private javax.swing.JLabel lbQuantidade;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbUnidadeMedida;
    private javax.swing.JLabel lbVendedor;
    private javax.swing.JTextArea taEndereco;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfNf;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfQuantidade;
    // End of variables declaration//GEN-END:variables
}
