/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import api.Janela;
import controller.CCategoria;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import tipos.TCategoria;

/**
 *
 * @author leo_m
 */
public class VCadastroCategoria extends javax.swing.JFrame {

    private void preCarregamento() {

        try {
            List<TCategoria> cat = new TCategoria().getCategorias();
            for (TCategoria i : cat) {
                cbSubCategoria.addItem(i);
            }
        } catch (SQLException ex) {
            Logger.getLogger(VCadastroProduto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void preencheCategoria() {
        categoria.setCategoria(tfCategoria.getText());
        if (ckSemSubCategoria.isSelected()) {
            categoria.setSubCategoria(null);
        } else {
            TCategoria subcategoria = (TCategoria) cbSubCategoria.getSelectedItem();
            categoria.setSubCategoria(subcategoria.getId());
        }
    }

    private boolean verificaCampos() {
        Janela janela = new Janela();
        return janela.exigeCampo(lbCategoria, tfCategoria);
    }

    private void iniciaComponentes() {
        categoria = new TCategoria();
        controller = new CCategoria();
//        preCarregamento();
        ckSemSubCategoria.setSelected(true);
        cbSubCategoria.setEnabled(false);
    }

    /**
     * Creates new form VCadastroCategoria
     */
    public VCadastroCategoria() {
        initComponents();
        iniciaComponentes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCategoria = new javax.swing.JPanel();
        tfCategoria = new javax.swing.JTextField();
        lbCategoria = new javax.swing.JLabel();
        lbSubCategoria = new javax.swing.JLabel();
        cbSubCategoria = new javax.swing.JComboBox<Object>();
        lbTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ckSemSubCategoria = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbCategoria.setText("Categoria");

        lbSubCategoria.setText("Sub-Categoria de:");

        lbTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbTitulo.setText("Cadastro de Categoria");

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ckSemSubCategoria.setText("Sem Sub-Categoria");
        ckSemSubCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckSemSubCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jCategoriaLayout = new javax.swing.GroupLayout(jCategoria);
        jCategoria.setLayout(jCategoriaLayout);
        jCategoriaLayout.setHorizontalGroup(
            jCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jCategoriaLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbSubCategoria)
                    .addComponent(lbCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitulo)
                    .addGroup(jCategoriaLayout.createSequentialGroup()
                        .addGroup(jCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfCategoria)
                            .addComponent(cbSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ckSemSubCategoria))
                    .addGroup(jCategoriaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jCategoriaLayout.setVerticalGroup(
            jCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jCategoriaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbTitulo)
                .addGap(18, 18, 18)
                .addGroup(jCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCategoria))
                .addGap(18, 18, 18)
                .addGroup(jCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSubCategoria)
                    .addComponent(cbSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckSemSubCategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (verificaCampos()) {
            preencheCategoria();
            if (controller.cadastraCategoria(categoria)) {
                this.dispose();
            }
        } else {

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ckSemSubCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckSemSubCategoriaActionPerformed
        if (ckSemSubCategoria.isSelected()) {
            cbSubCategoria.removeAllItems();
            cbSubCategoria.setEnabled(false);
        } else {
            cbSubCategoria.setEnabled(true);
            cbSubCategoria.removeAllItems();
            preCarregamento();
        }
    }//GEN-LAST:event_ckSemSubCategoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCadastroCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCadastroCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCadastroCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCadastroCategoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCadastroCategoria().setVisible(true);
            }
        });
    }

    private CCategoria controller;
    private TCategoria categoria;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Object> cbSubCategoria;
    private javax.swing.JCheckBox ckSemSubCategoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jCategoria;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbSubCategoria;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField tfCategoria;
    // End of variables declaration//GEN-END:variables
}
